### ISSUE TITLE
Removing / ignoring the state queuing and done

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#13]
Think it might be a good idea to remove the state queuing and done from the executioner. I wrote these initially because it's good for a stateless messaging system, but now we have this `submission` document, queuing is just when both `judged` and `error` are both false, and `done` is just when `judged` or `error` is true. 

@Daniel5055 is this difficult to refactor? If it is, just ignore it, we can just simply ignore `queuing` and `done` downstream.

**Comment by Daniel5055** [comment]
Nope, this is fine! This will likely only result in about 4 lines of code changed, so I can change that when I get home
