### ISSUE TITLE
Tally Score as Part of the Executioner

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#14]
Previously I was planning to use cloud function to tally the score in order to decouple the code but now I just realised that using cloud functions that writes into the same database that triggers the function is very dangerous. I can easily create with a recursive bomb that end up [costing me $72k](https://news.ycombinator.com/item?id=25372336). 

@Daniel5055 Can we implement this in the executioner? I think we can just write in the submission document

```
failedSubtasks: array of integers, counting from 1
score: received score of the total score (total is always 1)
```

**Comment by Daniel5055** [comment]
Yup, I can add that. To clarify, if sub task 1 fails then I append 1 to the failed subtasks array on the document right? Also what is meant by score? And how can I determine the value of each sub task?

**Comment by DE0CH** [comment]
Thanks. 

> To clarify, if sub task 1 fails then I append 1 to the failed subtasks array on the document right? Also what is meant by score?

Yep.

> Also what is meant by score? And how can I determine the value of each sub task?

Each subtask is worth a portion of the total score of a question (a question is wroth 1 mark). It's defined in `statement.md` and complied to `statement.json` with `python3 problems/compile_statement.py [problem-id]`. It's in the field `subtasks[subtaskNumber].score`. You can check out `inequality-check/statement.json` for an example.

**Comment by DE0CH** [comment]
Also can you please also add a subtask field (if there is a subtask) to each `testing` and `tested` `judge-result`?

**Comment by DE0CH** [comment]
We also need to add a few more states to the submission doc. This is mostly so that we can display the judging status in a table of many submissions without convoluted frontend logic to grab the latest judge result from the database.

- compiling
- compiled
- judging
- judged
- error

~~Also see #18 for an alternative way of implementing the states.~~ We will implement it with a `state` as a enum.

**Comment by DE0CH** [comment]
See `tools/dummies/judge_result` for an example.

**Comment by Daniel5055** [comment]
@DE0CH I have pushed a proto version of score tallying. I'm pretty sure it works at least with tests without subtasks although I have not tested it with subtasks yet. If everything works correctly, it should do everything required for score tallying. I'm working on adding various new subtask tests but for now, if it doesn't work then just use an older commit.

**Comment by Daniel5055** [comment]
Tests for the score tallying have been created, and I've since fixed some some previously unidentified bugs with the tallying. Score tallying should now be working pretty well and stable.
