### ISSUE TITLE
State in Submission Doc

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#18]
I realised that currently the submission doc is using one-hot encoding for the state. Not sure if this is a good idea because there are a lot of illegal states. The alternative is to use a string for the state that functions as an enum. In terms of the frontend, both are equally straightforward to implement. What do you think @Daniel5055. Which do you prefer?

**Comment by Daniel5055** [comment]
Yeah sounds good. Should be pretty straight forward to implement in the executioner interface. String enums are also more flexible, allowing for the addition of more state if ever needed.

**Comment by DE0CH** [comment]
Great. Sounds good. Just to summarise, we have the following states

- compliling
- compiling
- judging
- judged
- error
