### ISSUE TITLE
Add support for multiple executioner units

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#2]
We can make it so that we can connect multiple executioner units at the same time to improve uptime and scalability. I thought to add a field called "judging" in the submission and write to that with firebase transaction to prevent racing conditions. Also we can have a document `/info/info` which stores executionerCount and when it goes down to 0 the frontend would alert the user the the executioner is not up. Though we can add this feature later after we are done with more important things.

**Comment by Daniel5055** [comment]
Although I haven't added any support for the executioner signalling start and shutdown yet, the possibility of running multiple executioners now works. Executioners all read from the same firestore and if they can, they'll try to execute a submission by making a firestore transaction. If that fails then another executioner is likely already executing it.
