### ISSUE TITLE
Need to Ignore Whitespaces in Submission

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#23]
The output from the user doesn't need to exactly match the output of the answer. Trailing and leading whitespace should be ignored and multiple consecutive whitespace should be treated as one. For example

```
a b     c
``` 
is the same as 
```
   a   b  c
```

I would suggest that we have a clearly decoupled comparison function `compareAnswers(userAnswer, correctAnswer)` which returns true iff the two answers are the same. This would make way for us eventually adding computed answer (answers that need to be checked with logic) such as finding the most optimal combination.

**Comment by DE0CH** [comment]
For example, this code fails Even Odd Check
```python
n = int(input())

if n % 2 == 0:
  print("even ") # Notice the trailing space
else:
  print("odd")
```

**Comment by Daniel5055** [comment]
Oh yup, I was expecting this hahaha. Currently the executioner does a strict equality check between strings.

**Comment by Daniel5055** [comment]
I agree with the decoupled function idea, and I'll get on that

**Comment by DE0CH** [comment]
Wait, please see comment on https://github.com/CP-STA/STAOJ/pull/35#issuecomment-1233958478
