### ISSUE TITLE
New typo: Runtime Errror

### ISSUE THREAD

**Issue by kay-liechtenstein** [CP-STA/STAOJ#26]
In judgement, Runtime Errror → Runtime Error

**Comment by DE0CH** [comment]
Lol looks like I really need to use a spell check. 

It's been fixed now.

**Comment by kay-liechtenstein** [comment]
Sarcastic that “error” was an error. 
Thanks a lot anyway.

**Comment by DE0CH** [comment]
sarcastic indeed 😭
