### ISSUE TITLE
Error Handling for Finding Problem

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#27]
I forgot to pull the problem repository so I got this bug:

```
5HAHA88FZq27T0ehfUy3: queuing
5HAHA88FZq27T0ehfUy3: error
Error: Problom directory /home/deyaoc/STAOJ/problems/inequality-check not found
    at file:///home/deyaoc/STAOJ/executioner/src/executor.mjs:90:11
    at async execute (file:///home/deyaoc/STAOJ/executioner/src/executor.mjs:89:3)
    at async handleExecution (file:///home/deyaoc/STAOJ/executioner/src/executioner.mjs:67:24)
    at async pushRequest (file:///home/deyaoc/STAOJ/executioner/src/executioner.mjs:90:7)
```
And the entire executioner exited. This shouldn't really be the behaviour. If the problem repo is not found, it should just return an error for the specific submission, not crashing the entire program. Also I think it should look for the problem in the `problem-private` repo in case the user is submitting for a contest problem.

**Comment by Daniel5055** [comment]
Problems-private is now the default and caught errors like that no longer cause the executioner to exit
