### ISSUE TITLE
Compilation Error Not Showing

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#28]
I tried to submit some gibberish for inequality check but instead of giving me a compilation error, it goes to judged with score of 1. Perhaps some logic fell through?

**Comment by Daniel5055** [comment]
Oh yes definitely, I know exactly how hahaha. When execution finishes without exceptions, a 'done' message is sent internally which sets to judged. So I have to fix that. Also I had only set failures to occur when tests failed and had not forgotten compilation errors as a possibility.
