### ISSUE TITLE
Executioner Status & Shutdown Procedure

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#3]
The user might want to know if the executioner is on. We should block submission if it is not on and tell the user an alternative way to submit. 

Also, before the executioner needs to be shutdown, it should first block any new submission and finish judging all the submissions in the queue. I think this needs two parts.

1. Some kind of signal to the excutioner to begin a shutdown. I'll leave this to you @Daniel5055. 
2. In `info/info` document in firestore, have a field called `judgeCount` which is 0 if it is off or beginning to shutdown, and 1 otherwise. This would make way for eventually implementing #2 . 
3. Security rules that deny adding more submission if excutioner is not on.
4. Some frontend logic to display the information nicely.

Also should the executioner clean up the backlog of submission (those marked as `judged: false`) when it starts up? If we implement this feature, there shouldn't really be a backlog so I'm not really sure if we should ignore this or not. Perhaps we should mark `error: true` because it shouldn't really happen normally?

**Comment by Daniel5055** [comment]
Sounds like a good idea. Notifying Firestore about the state of the executioner shouldn't be hard.

With regards to the backlog. There exists an option when creating the interface called readOld. By default this is false but when true, the executioner will handle all previous unjudged submissions with no errors before continuing.

I haven't implemented any way to call this feature from the command line, yet it the does exist.

**Comment by Daniel5055** [comment]
I've added steps 1 and 2 to the executioner so it will now notify firestore on startup and shutdown by updating the `judgeCount` field in `info/info`. I used this field instead as I noticed it already existed in the main firestore db.

Notably, I have not yet implemented the executioner awaiting submissions to finish before exiting, or preventing reading any further submissions. Currently, when it exits, it will update the `judgeCount` field and then exit immediately.

The executioner will intercept observable exit signals like `SIGINT` and `SIGTERM` and call the cleanup then before exiting. So calling something like `Ctrl-c` will trigger a cleanup. Uncaught exceptions or errors causing the process to exit will also trigger a cleanup.

**Comment by DE0CH** [comment]
I see. It looks really good so far. Thanks. I just realised I used the wrong name in `info/info` haha. Forgot about what it should have been. Let's just keep it this way then.

Will the executioner finish judging the current submission when it exists? I think it shouldn't try to clear up the queue because there should be another executioner already running when we turn one off for maintenance / update. 

I currently use systemd to start and stop the executioner so supporting SIGTERM would be good. Also systemd sends a SIGKILL after 90 seconds, so we should aim to exit within that time (which should be plenty). 

What does a cleanup include? Does it include clearing up all the judge-results of a judging submission and flipping the state back to queued?

**Comment by Daniel5055** [comment]
Currently I haven't added support for most of what is mentioned but I'll be adding that today. Currently cleanup is just notifying the db and exiting. If a submission is running it will exit anyway. So yeah I'll make the executioner await for the remaining submissions to run first and also stop reading any more submission. Luckily the executioner does read SIGTERM.

**Comment by Daniel5055** [comment]
I have resolved this issue on the backend side now completely, although I don't know if part 4 is done already in the frontend. For part 3, the executioner will not read anymore submissions if it is shutting down, though I don't know if any security rules are in place on the firestore side

**Comment by DE0CH** [comment]
You're right. The answer is no and no. I'll get onto that.

**Comment by DE0CH** [comment]
Firebase rules have been updated. Closing issue as complete.
