### ISSUE TITLE
State Stuck in Judging

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#31]
I submitted a wrong submission, and all the runs returned runtime error. At the end the score is 0 but the state is stuck in judging.

<img width="771" alt="Screenshot 2022-08-31 at 01 28 39" src="https://user-images.githubusercontent.com/40887572/187505038-46014008-3c58-45fa-9d2e-a488714734b8.png">

**Comment by Daniel5055** [comment]
Interesting, I wonder how this could have happened. I'm writing a mock firestore interface so I should be able to test this better in a bit. Meanwhile, what was the source code and language? And does this happen for all wrong submissions?

**Comment by DE0CH** [comment]
I think it does happen for all wrong submission. Language is python and source code is 

```
<script>alert(1)</script>
```

I was trying to check XSS haha.
