### ISSUE TITLE
Executioner Seems to Have Written to the Wrong Document

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#32]
The judge sometimes write what should be in a `judge-result` document into the submission document and vice versa. 

<img width="1288" alt="Screenshot 2022-09-01 at 00 45 42" src="https://user-images.githubusercontent.com/40887572/187733781-ef6750e0-d999-42ea-8221-f9664c884b3b.png">

I guess this was caused by 9b35722.

Since we are approaching our launch day, it might be good to keep the executioner online. So you might want to create your own firebase firestore for testing. See [README.md](<img width="1288" alt="Screenshot 2022-09-01 at 00 45 42" src="https://user-images.githubusercontent.com/40887572/187733781-ef6750e0-d999-42ea-8221-f9664c884b3b.png">) for more details. 

Currently the content of the pages are very tightly coupled with the `contest-problems` repo. I aim to change that to use local files to make it faster and make local development and testing easier. Since changing that will likely cause some bugs, I think I will change that after v1.0. For now, you can just search for `raw.githubusercontent.com` and replace the contents accordingly.

**Comment by Daniel5055** [comment]
I yes, I see I must have accidentally swapped the update state and add result functions. This will be resolved in a sec once the tests finish running. And yup, creating a firestore for testing is quite a good idea.
