### ISSUE TITLE
Executioner Stuck in Queuing

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#36]
The executioner doesn't seem to be judging the submission. It's stuck in queuing. 

```
New submission: rhKI9D1moSBNZSM170je 
 {
  submissionTime: Timestamp { _seconds: 1662001108, _nanoseconds: 889000000 },
  user: 'iKshqxUmP5TdNXJq1ml6UdaBYm42',
  state: 'queued',
  problem: 'inequality-check',
  language: 'python-3.10',
  subtasksCount: 3,
  sourceCode: 'print("hello world")\n\n',
  problemName: 'Inequality Check'
} rhKI9D1moSBNZSM170je
rhKI9D1moSBNZSM170je: queuing
```

**Comment by Daniel5055** [comment]
I feel like this might be an issue with the queuing system I've implemented, fortunately I've already started writing tests for that and have been working on allowing for multiple submissions to be handled simultaneously
