### ISSUE TITLE
Executioner Stuck in Testing

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#40]
Not sure if I messed something up, but when I ran the executioner, the submission state is stuck in judging without any test case from being run. 

Did you test this on your own computer, did it work?

**Comment by Daniel5055** [comment]
Huh that's odd. Yeah I tested using the Firestore test db and website and didn't have any problems. Is this always the case or did a specific submission cause this? And were you running multiple executioners?

**Comment by Daniel5055** [comment]
This sounds like it could have been caused from exiting the executioner before a submission has finished testing. I mention this in #3.

**Comment by Daniel5055** [comment]
Apparently having `--cpu 1` made the executioner not work for anything outside of the dev container. Weird.
