### ISSUE TITLE
Demoter Failed to Capture Stderr

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#46]
The demoter / run script does not capture the stderr from the program. Not sure if I did logging wrong.

**Comment by Daniel5055** [comment]
Is this a new bug or has it existed before?

**Comment by DE0CH** [comment]
I never checked the stderr before. I checked it to fix TLE spoofing, but found out that the stderr from the program was not captured.

**Comment by Daniel5055** [comment]
I'm not quite sure what you mean. Stderr is directed to the same stderr as the demoter? The following attachment shows only the stderr of the executed program `bash -c hello`:
![image](https://user-images.githubusercontent.com/29730245/188705478-542bd195-1aee-423c-9452-3dc7a29d8727.png)

Also the run scripts rely on reading the program stderr to determine if it was an MLE, and they appear to do so successfully in tests.

**Comment by DE0CH** [comment]
I might have messed something up when trying to read from stderr. I'll close this issue.
