### ISSUE TITLE
Lock apt package versions

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#48]
The Dockefile just gets the newest version of a package whenever the image is built. This can lead to mismatch between the version we tell users in supported-langauges.json.

**Comment by Daniel5055** [comment]
Good point, I've never specified a package version when downloading so I'm not sure if its possible but I'll check it out

**Comment by DE0CH** [comment]
Turns out I was complete wrong about this. Debian is not a rolling release (should've known that lol), so the package versions are locked minus the security updates. So this is not an issue in the first place. I was being dumb.
