### ISSUE TITLE
Problem folder not found crashes executioner

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#50]
```
Uncaught exception in executioner:
Error: Problom directory /home/deyaochen/STAOJ/problems-private/climbing-a-ladder not found
    at file:///home/deyaochen/STAOJ/executioner/src/executor.mjs:114:11
    at async execute (file:///home/deyaochen/STAOJ/executioner/src/executor.mjs:113:3)
    at async handleExecution (file:///home/deyaochen/STAOJ/executioner/src/executioner.mjs:122:24)

Cleaning up...
Awaiting 0 requests to finish
Goodbye
npm notice 
npm notice New minor version of npm available! 8.15.0 -> 8.19.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.19.1
npm notice Run npm install -g npm@8.19.1 to update!
npm notice 
```
Since a user can spoof the problem id, we don't want it crash the entire executioner.

**Comment by DE0CH** [comment]
With PR #55, executioner should not be crashed, but the output is still messed up. But it doesn't really matter because if we ever end up in that case, we messed up big time and it doesn't matter if we display the error nicely.

**Comment by Daniel5055** [comment]
Yeah I've currently been rather basic with errors. It just throws error objects (which contain the strack trace etc) and I just print those. I should also technically rename the error from uncaught exception because it isn't uncaught as that's a custom error message. I'll probably added a default option to remove the stack trace also to make it looker prettier

**Comment by DE0CH** [comment]
I'd say not to spend too much time with error handling. To quote Dennis Ritchie:

> I remarked to Dennis that easily half the code I was writing in Multics was error recovery code. He said, "We left all that stuff out. If there's an error, we have this routine called panic, and when it is called, the machine crashes, and you holler down the hall, 'Hey, reboot it.'
