### ISSUE TITLE
Executioner Getting stuck on Testing

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#51]
The executioner seems to be stuck on testing for some test cases. I suspect it has to do with podman, perhaps the number of container is limited. It is different for different machines. For the production aws ec2 it gets stuck on test 242 and for the one I'm using it gets stuck on 210.

**Comment by DE0CH** [comment]
For now I've just limited the number of test case to 200. So we can kick this bug down the road.

**Comment by Daniel5055** [comment]
Hmm seems odd. All tests are run in a single container and the max limit of containers is 2048 by default. Containers are deleted after being run anyway so it should never max out.

Hmm very interesting

**Comment by DE0CH** [comment]
Also it only gets stuck on TLE. If all the tests finish in time, all is good.

**Comment by Daniel5055** [comment]
Hmmm could be a hanging promise somewhere. I've been settling in my halls during the weekend but I'll take a look soon.

**Comment by Daniel5055** [comment]
Hmm. So far I am unable to recreate this @DE0CH. I've created a test problem called test-256 with 256 test cases and I haven't gotten the executioner to get stuck on testing yet. I've tested it with a submission that always passes its tests, a submission that will always trigger TLE, and I'm currently awaiting the submission that hangs every test to finish.

As one may expect, the TLE submissions take quite a while for 256 testcases

**Comment by DE0CH** [comment]
That's quite strange. We should probably arrange a meeting sometime to take a look at this together, but I guess since school's starting and it isn't really a critical bug, we can put this aside for a while.

**Comment by Daniel5055** [comment]
![image](https://user-images.githubusercontent.com/29730245/190700860-6fc97597-0263-4aa3-abff-8a972a74cd39.png)
Found the same issue finally randomly, except it got stuck at 196...

**Comment by DE0CH** [comment]
I think it might be because my EC2 instance is running out of memory. It only has 1GB in total...
