### ISSUE TITLE
executioner run with systemctl does not exit correctly

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#54]
Somehow if I use systemctl to stop the executioner, the judging get stuck in testing.

**Comment by Daniel5055** [comment]
@DE0CH does the executioner say clean up when trying to exit? If not then it could be I haven't handled a signal. If it does say cleanup but then gets stuck then I haven't got a clue and that'll be fun to fix

**Comment by DE0CH** [comment]
Yeah I checked the log. The executioner prints the normal "waiting for 1 submission to finish" and then just hang. 

Please don't worry about fixing it now. I just run the executioner in a screen so I can stop it with control c. The only down side is that there's no automatic restart like it can with systemctl. But if everything goes well, it shouldn't stop in the first place, so all is good.

**Comment by Daniel5055** [comment]
@DE0CH When you are referring to using systemctl with the executioner, do you mean like creating service files? I'm trying to recreate this bug

**Comment by DE0CH** [comment]
I mean launching and stopping the executioner with systemctl. See below for the service file:

```
[Unit]
Description="STAOJ executioner"

[Service]
User=admin
WorkingDirectory=/home/admin/STAOJ/executioner
ExecStart=npm start
Restart=always
TimeoutStopSec=infinity
KillSignal=SIGINT
```

**Comment by Daniel5055** [comment]
Alright perfect, I started writing a service file to run the executioner until I realised I couldn't run systemd within the dev container so I'll be testing that outside of there.

Interesting though, SIGINT should be one of the captured signals.
