### ISSUE TITLE
Proper Setup of Monaco editor

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#6]
Right now the monaco editor doesn't have any worker and gives warnings such as 
```
Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/microsoft/monaco-editor#faq
```
and 
```
You must define a function MonacoEnvironment.getWorkerUrl or MonacoEnvironment.getWorker
```

The editor works and still has syntax highlighting (except for #5), but it doesn't seem to have any good auto completion. 

Also It loads in a hacky way. Not sure it is tree shook.

**Comment by DE0CH** [comment]
Also I also want to ask anyone who knows if js dynamic import caches the import. i.e. if I call `import()` twice, will the second time take as long as the first time? Since I am not sure, currently I have a manual caching setup in `frontend/src/lib/MonacoBlock.svelte`:

```javascript
	let monaco;
	async function getMonaco() {
		if (!monaco) {
			monaco = await import('monaco-editor');
		}
		return monaco;
	}
```

Is this really needed?

**Comment by quangvn2508** [comment]
According to this [post](https://dmitripavlutin.com/javascript-module-import-twice/#:~:text=If%20a%20module%20is%20imported,receive%20the%20same%20module%20instance.), the subsequent `import()` wouldn't take as long since the module is evaluated the first time.

**Comment by DE0CH** [comment]
I see. Interesting. Since it works now, i'd prefer not to touch for now.

**Comment by quangvn2508** [comment]
I look around for the auto-completion, but I don't think there's any add-on for C++ syntax. To be fair, I don't think people will use it as a place for development anyway. Like Codeforces, we just want users to work locally and submit. Unless we want the contest to be like Leetcode, then maybe auto-completion is prefered.
