### ISSUE TITLE
Submissions that intentionally timeout could take ages

### ISSUE THREAD

**Issue by Daniel5055** [CP-STA/STAOJ#60]
The typical time limit (and minimum actually) of a problem is 1 second. Say there are 200 test cases for that problem. A submission that exceeds the time limit of each test would take at least **200 seconds** to complete.

If a submissions exceeds the time limit of each test by hanging then it would take at least **600 seconds** to complete as the real-time limit is 3 times the cpu time limit. In fact, as I write this I am actually running a submission for a 200 test case problem that is currently only on 152/200 test cases.

Submissions that take this long could pollute the executioner queue and make proper submissions take ages.

Unfortunately, I don't really have a good solution against this right now. Here are some ideas I have thought of:

1. We could just set the real time limit to 1 or 1.5 time the time limit yet that's still a submission that would take at least 3 to 5 min.

2. Instead cap the overall real time limit of a submission to something like (time limit) * (test cases). This would at least limit the time to around 3.3 min max for 200 test cases regardless of what the submission is.

3. Reduce the number of test cases in a problem. This of course could be combined with some of the other solutions

4. Stop running a subtask of tests if the submission fails. In theory programs could still take a while if they carefully use up to the limits effectively yet this is much less likely. Regardless this would prevent simple submissions calling `sleep` etc from taking ages as they will just fail the first test of each subtask and then finish.

I bring this point up after trying to resolve #51 and finding that submissions that reach TLE take ages.

**Comment by DE0CH** [comment]
I think point 4 is a good idea. To make it nice to render on the frontend, the executioner should skip all the test cases and send a testing message followed by a tested message with "skipped" as the result for the skipped test cases if one in the subtask fails. 

As for deliberate attacks, I don't think we need to worry about those because I think the likelihood of that happening is quite small.
